name:  Auto Statistics
permissions:
  contents: write
on:
  push:
    branches:
    -  main
# on:
#   schedule:
#     - cron: 0 2 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5 
      with:
        python-version: 'pypy3.9' 
    - run: |
        pip install lxml
        python main.py "${{ secrets.U2_URL }}" "${{ secrets.U2_COOKIE }}" "${{ secrets.TTG_URL }}" "${{ secrets.TTG_COOKIE}}" "${{ secrets.PTER_URL }}" "${{ secrets.PTER_COOKIE}}" "${{ secrets.MT_URL }}" "${{ secrets.MT_AUTH}}" "${{ secrets.HD_URL }}" "${{ secrets.HD_COOKIE}}"
        git config --global user.email "riverage@163.com"
        git config --global user.name "github actions"
        git add .
        git commit -m  "update @`TZ=Asia/Shanghai date "+%Y-%m-%d %H:%M:%S"`"
        git push
    
