name:  Auto Sign
permissions:
  contents: write
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5 
      with:
        python-version: 'pypy3.9' 
    - run: |
        pip install lxml
        python main.py "${{ secrets.U2_COOKIE }}" "${{ secrets.TTG_COOKIE}}"
        git config --global user.email "riverage@163.com"
        git config --global user.name "github actions"
        git add .
        git commit -m  "update @`TZ=Asia/Shanghai date "+%Y-%m-%d %H:%M:%S"`"
        git push
    
