name:  Auto Sign
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5 
      with:
        python-version: 'pypy3.9' 
    - run: |
        pip install lxml
        python main.py ${{ secrets.U2_COOKIE }} ${{ secrets.TTG_COOKIE}}
        ls -alsh
        git add .
        git commit -m 'update'
        git push
    
